[development]
grant_type = "client_credentials"
client_id = "INSTANCE_client"
client_secret = "super_secret_client_secret"
customer_instance = "INSTANCE"

[production]
grant_type = "client_credentials"
client_id = "INSTANCE_client"
client_secret = "super_secret_client_secret"
customer_instance = "INSTANCE"
